In [1]:
l=[23245, 27, 546, 215, -1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
import numpy as np

In [4]:
a=np.array(l)

In [5]:
a

array([23245,    27,   546,   215, -1234])

In [6]:
b=np.array([12,455,63.3,True,"abc"])

In [7]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [8]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [9]:
l.pop()

-1234

In [10]:
l

[23245, 27, 546, 215]

In [11]:
a.mean()

4559.8

In [12]:
l

[23245, 27, 546, 215]

In [13]:
l[1:]

[27, 546, 215]

In [14]:
l[0:2]

[23245, 27]

In [15]:
l[::2]

[23245, 546]

In [17]:
a

array([23245,    27,   546,   215, -1234])

In [18]:
a[2:]

array([  546,   215, -1234])

In [19]:
a[2:4]

array([546, 215])

In [20]:
b=a[2:4]

In [21]:
b

array([546, 215])

In [22]:
b[0]

546

In [23]:
b[:]

array([546, 215])

In [24]:
b[:]=111

In [25]:
b

array([111, 111])

In [26]:
a

array([23245,    27,   111,   111, -1234])

In [27]:
c=a.copy()

In [28]:
c

array([23245,    27,   111,   111, -1234])

In [29]:
c[0]=0

In [30]:
c

array([    0,    27,   111,   111, -1234])